# Generated by Django 5.2.8 on 2025-11-30 01:59

import core.models
import core.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Optional. Enter phone number in international format.', max_length=20, validators=[core.validators.validate_phone_number], verbose_name='phone number')),
                ('university_name', models.CharField(blank=True, default='', help_text='Educational institution name.', max_length=200, verbose_name='university name')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('provider', 'Service Provider')], help_text='Required. Select whether you are a student or service provider.', max_length=10, verbose_name='user type')),
                ('profile_image', models.ImageField(blank=True, help_text='Optional. Upload a profile picture (max 5MB, formats: jpg, png, webp).', null=True, upload_to=core.models.user_profile_image_upload_path, validators=[core.validators.validate_profile_image], verbose_name='profile image')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates whether a service provider has been verified.', verbose_name='verified status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the account was last updated.', verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MovingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the moving service', max_length=200, verbose_name='service name')),
                ('description', models.TextField(help_text='Detailed description of the service', verbose_name='description')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the service in USD', max_digits=10, verbose_name='base price')),
                ('availability_status', models.BooleanField(default=True, help_text='Whether the service is currently available', verbose_name='availability status')),
                ('rating_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating from 0.00 to 5.00', max_digits=3, verbose_name='rating average')),
                ('total_reviews', models.PositiveIntegerField(default=0, help_text='Total number of reviews received', verbose_name='total reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the service was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the service was last updated', verbose_name='updated at')),
                ('provider', models.ForeignKey(help_text='Provider offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moving service',
                'verbose_name_plural': 'moving services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(help_text='Date and time when the service is scheduled', verbose_name='booking date')),
                ('pickup_location', models.CharField(help_text='Address for pickup', max_length=300, verbose_name='pickup location')),
                ('dropoff_location', models.CharField(help_text='Address for dropoff', max_length=300, verbose_name='dropoff location')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the booking', max_length=20, verbose_name='status')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the booking in USD', max_digits=10, verbose_name='total price')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the booking was last updated', verbose_name='updated at')),
                ('provider', models.ForeignKey(help_text='Provider offering the service', on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student making the booking', on_delete=django.db.models.deletion.CASCADE, related_name='student_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.movingservice')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='core_user_user_ty_e1e849_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='core_user_is_veri_959b73_idx'),
        ),
        migrations.AddIndex(
            model_name='movingservice',
            index=models.Index(fields=['provider'], name='core_moving_provide_365bce_idx'),
        ),
        migrations.AddIndex(
            model_name='movingservice',
            index=models.Index(fields=['availability_status'], name='core_moving_availab_428776_idx'),
        ),
        migrations.AddIndex(
            model_name='movingservice',
            index=models.Index(fields=['rating_average'], name='core_moving_rating__e9bf65_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student'], name='core_bookin_student_bc6816_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider'], name='core_bookin_provide_efc32b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service'], name='core_bookin_service_ea8e27_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='core_bookin_status_fe12a1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='core_bookin_booking_34a7f2_idx'),
        ),
    ]
