# Generated by Django 5.2.8 on 2025-12-02 09:41

import core.models
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the furniture item', max_length=200, verbose_name='title')),
                ('description', models.TextField(help_text='Detailed description of the item', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD (must be greater than 0)', max_digits=10, verbose_name='price')),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Condition of the item', max_length=20, verbose_name='condition')),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('appliances', 'Appliances'), ('electronics', 'Electronics'), ('books', 'Books'), ('clothing', 'Clothing'), ('other', 'Other')], help_text='Category of the item', max_length=20, verbose_name='category')),
                ('is_sold', models.BooleanField(default=False, help_text='Whether the item has been sold', verbose_name='is sold')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the item was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the item was last updated', verbose_name='updated at')),
                ('seller', models.ForeignKey(help_text='User selling this item', on_delete=django.db.models.deletion.CASCADE, related_name='furniture_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'furniture item',
                'verbose_name_plural': 'furniture items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file (max 5MB, formats: jpg, png, webp)', upload_to=core.models.furniture_image_upload_path, validators=[core.validators.validate_profile_image], verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for images', verbose_name='order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the image was uploaded', verbose_name='uploaded at')),
                ('furniture_item', models.ForeignKey(help_text='Furniture item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.furnitureitem')),
            ],
            options={
                'verbose_name': 'furniture image',
                'verbose_name_plural': 'furniture images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FurnitureTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_status', models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('released', 'Released')], default='pending', help_text='Current status of escrow', max_length=20, verbose_name='escrow status')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when transaction was created', verbose_name='transaction date')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when escrow was released', null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transaction was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the transaction was last updated', verbose_name='updated at')),
                ('buyer', models.ForeignKey(help_text='User purchasing the item', on_delete=django.db.models.deletion.CASCADE, related_name='furniture_purchases', to=settings.AUTH_USER_MODEL)),
                ('furniture_item', models.ForeignKey(help_text='Furniture item being transacted', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.furnitureitem')),
                ('seller', models.ForeignKey(help_text='User selling the item', on_delete=django.db.models.deletion.CASCADE, related_name='furniture_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'furniture transaction',
                'verbose_name_plural': 'furniture transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='furnitureitem',
            index=models.Index(fields=['seller'], name='core_furnit_seller__50d11f_idx'),
        ),
        migrations.AddIndex(
            model_name='furnitureitem',
            index=models.Index(fields=['is_sold'], name='core_furnit_is_sold_47be15_idx'),
        ),
        migrations.AddIndex(
            model_name='furnitureitem',
            index=models.Index(fields=['category'], name='core_furnit_categor_33cdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='furnitureitem',
            index=models.Index(fields=['condition'], name='core_furnit_conditi_01d4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='furnitureimage',
            index=models.Index(fields=['furniture_item'], name='core_furnit_furnitu_b1fd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='furnitureimage',
            index=models.Index(fields=['order'], name='core_furnit_order_13abbd_idx'),
        ),
        migrations.AddIndex(
            model_name='furnituretransaction',
            index=models.Index(fields=['buyer'], name='core_furnit_buyer_i_2f5985_idx'),
        ),
        migrations.AddIndex(
            model_name='furnituretransaction',
            index=models.Index(fields=['seller'], name='core_furnit_seller__45ceb6_idx'),
        ),
        migrations.AddIndex(
            model_name='furnituretransaction',
            index=models.Index(fields=['furniture_item'], name='core_furnit_furnitu_6c101f_idx'),
        ),
        migrations.AddIndex(
            model_name='furnituretransaction',
            index=models.Index(fields=['escrow_status'], name='core_furnit_escrow__0b681e_idx'),
        ),
        migrations.AddIndex(
            model_name='furnituretransaction',
            index=models.Index(fields=['transaction_date'], name='core_furnit_transac_57d364_idx'),
        ),
    ]
