# Generated by Django 5.2.8 on 2025-12-02 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_furnitureitem_furnitureimage_furnituretransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rating must be at most 5.')], verbose_name='rating')),
                ('comment', models.TextField(help_text='Written feedback about the experience', verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created', verbose_name='created at')),
                ('booking', models.ForeignKey(help_text='Booking being reviewed (one review per booking)', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.booking', unique=True)),
                ('reviewee', models.ForeignKey(help_text='User receiving the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='User writing the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewer'], name='core_review_reviewe_b47e35_idx'), models.Index(fields=['reviewee'], name='core_review_reviewe_2f8ae2_idx'), models.Index(fields=['booking'], name='core_review_booking_36288f_idx'), models.Index(fields=['rating'], name='core_review_rating_41e437_idx'), models.Index(fields=['created_at'], name='core_review_created_25a366_idx')],
            },
        ),
    ]
