# Generated by Django 5.2.8 on 2025-12-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(help_text='Booking being reviewed (one review per booking)', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.booking'),
        ),
    ]
