# Generated by Django 5.2.8 on 2025-12-09 01:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_unique_booking_per_service_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_rating_as_provider',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating when acting as a service provider.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Rating cannot be negative.'), django.core.validators.MaxValueValidator(Decimal('5.00'), message='Rating cannot exceed 5.00.')], verbose_name='average rating as provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='avg_rating_as_student',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating when acting as a student.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Rating cannot be negative.'), django.core.validators.MaxValueValidator(Decimal('5.00'), message='Rating cannot exceed 5.00.')], verbose_name='average rating as student'),
        ),
    ]
