# Generated by Django 5.2.8 on 2025-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_user_rating_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the review was last updated', verbose_name='updated at'),
        ),
    ]
