# Generated by Django 5.2.8 on 2025-12-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(help_text='Booking being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.booking'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'booking'), name='unique_reviewer_per_booking'),
        ),
    ]
