# Generated by Django 5.2.8 on 2025-12-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_review_booking_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_service_slot',
        ),
    ]
